### ISSUE TITLE
SideBar menu multilevel

### ISSUE THREAD

**Issue by lwazevedo** [start-javascript/sb-admin-material#2]
Hellow, 

Hi

Please consider including a multilevel menu option. Like the following image:

![selecao_002](https://user-images.githubusercontent.com/17619473/41573759-a1495d74-7354-11e8-82d2-167ab2a3351c.png)

I tried to do the following code, but I did not succeed.
sidebar.component.html
![selecao_004](https://user-images.githubusercontent.com/17619473/41573897-5bba465a-7355-11e8-9eda-18bde8cbf9b6.png)

Unfortunately it did not look pretty, as you can see in the image.
![selecao_005](https://user-images.githubusercontent.com/17619473/41573912-6d5bd478-7355-11e8-9f03-c488ddc4321b.png)

thank you.

**Comment by nkmdev** [comment]
https://stackblitz.com/angular/gkxdrnmpvjb?file=app%2Fnested-menu-example.ts
https://material.angular.io/components/menu/overview
please use angular material nested menu.
